# -*- coding: utf-8 -*-
"""Arithmetic_sample1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g0J74dJoBW6acldEzX3jpS-2TVdsoaRg
"""

import streamlit as st
import random

# Function to generate random arithmetic questions
def generate_questions():
    questions = []
    for _ in range(10):
        num1 = random.randint(10, 99)
        num2 = random.randint(10, 99)
        operator = random.choice(["+", "-"])
        question = f"{num1} {operator} {num2}"
        answer = eval(question)  # Calculate the correct answer
        questions.append((question, answer))
    return questions

# Streamlit app
def main():
    st.title("Arithmetic Quiz")
    st.write("Solve the following 10 questions. Enter your answers below:")

    # Generate questions and store in session state
    if "questions" not in st.session_state:
        st.session_state.questions = generate_questions()
        st.session_state.user_answers = [None] * 10  # Placeholder for user answers
        st.session_state.score = None  # Placeholder for score

    # Display the questions
    for i, (question, _) in enumerate(st.session_state.questions):
        st.write(f"Q{i + 1}: {question}")
        st.session_state.user_answers[i] = st.number_input(
            f"Your Answer for Q{i + 1}", key=f"answer_{i}", value=0
        )

    # Final Submit button
    if st.button("Final Submit"):
        score = 0
        for i, (_, correct_answer) in enumerate(st.session_state.questions):
            if st.session_state.user_answers[i] == correct_answer:
                score += 1
        st.session_state.score = score
        st.success(f"Your Score: {score} / 10")

# Run the app
if __name__ == "__main__":
    main()
