# -*- coding: utf-8 -*-
"""Arithmetic_sample1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g0J74dJoBW6acldEzX3jpS-2TVdsoaRg
"""

# Generate questions and store in session state