# -*- coding: utf-8 -*-
"""My first.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g0J74dJoBW6acldEzX3jpS-2TVdsoaRg
"""

import streamlit as st
import numpy as np

def calculate_scores(scores):
    """Calculates total and average scores."""
    total = np.sum(scores)
    average = np.mean(scores)
    return total, average

# --- Streamlit UI ---
st.title("Student Grading System")

name = st.text_input("Student Name:")
subject1 = st.number_input("Score for Subject 1:", min_value=0.0, max_value=100.0)
subject2 = st.number_input("Score for Subject 2:", min_value=0.0, max_value=100.0)
subject3 = st.number_input("Score for Subject 3:", min_value=0.0, max_value=100.0)
subject4 = st.number_input("Score for Subject 4:", min_value=0.0, max_value=100.0)
subject5 = st.number_input("Score for Subject 5:", min_value=0.0, max_value=100.0)

if st.button("Calculate"):
    try:
        scores = [subject1, subject2, subject3, subject4, subject5]
        total, average = calculate_scores(scores)
        result = "Pass" if average >= 50 else "Fail"

        st.write(f"Student: {name}")
        st.write(f"Total: {total}")
        st.write(f"Average: {average}")
        st.write(f"Result: {result}")
    except ValueError:
        st.error("Invalid input. Please enter numeric values.")
